version: '3.8'

x-var: &DB_NAME bbs_rails_db
x-var: &DB_USER bbs_rails_db_user
x-var: &DB_PASSWORD bbs_rails_db_p@ssw0rd

services:
  db:
    image: postgres:12
    environment:
      POSTGRES_DB: *DB_NAME
      POSTGRES_USER: *DB_USER
      POSTGRES_PASSWORD: *DB_PASSWORD
    ports:
      - 5432:5432
    volumes:
      - vol_db:/var/lib/postgresql/data
  app:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      DB_HOST: db
      DB_NAME: *DB_NAME
      DB_USER: *DB_USER
      DB_PASSWORD: *DB_PASSWORD
    ports:
      - 3000:3000
    volumes:
      - .:/myapp
      - vol_web_bundle:/usr/local/bundle
    depends_on:
      - db
volumes:
  vol_db:
  vol_web_bundle:
