version: '3.8'

x-var: &DB_NAME bbs_rails_db
x-var: &DB_USER bbs_rails_db_user
x-var: &DB_PASSWORD bbs_rails_db_p@ssw0rd
x-var: &TEST_DB_NAME bbs_rails_db

services:
  db:
    image: postgres:12
    environment:
      POSTGRES_DB: *DB_NAME
      POSTGRES_USER: *DB_USER
      POSTGRES_PASSWORD: *DB_PASSWORD
    ports:
      - 5432:5432
    volumes:
      - vol_db:/var/lib/postgresql/data
  test_db:
    image: postgres:12
    environment:
      POSTGRES_DB: *TEST_DB_NAME
      POSTGRES_USER: *DB_USER
      POSTGRES_PASSWORD: *DB_PASSWORD
    volumes:
      - vol_db:/var/lib/postgresql/data
  app:
    build: .
    command: |
      bash -c "
        bundle install --jobs=4 --retry=3 &&
        rm -f tmp/pids/server.pid &&
        bundle exec rails s -p 3000 -b '0.0.0.0'
      "
    environment:
      DB_HOST: db
      DB_NAME: *DB_NAME
      DB_USER: *DB_USER
      DB_PASSWORD: *DB_PASSWORD
    ports:
      - 3000:3000
    volumes:
      - .:/myapp
      - vol_web_bundle:/usr/local/bundle
      - vol_web_node_modules:/myapp/node_modules
    depends_on:
      - db
  webpack-dev-server:
    build: .
    command: |
      bash -c "
        yarn install &&
        yarn start --host 0.0.0.0
      "
    ports:
      - 8080:8080
    volumes:
      - .:/myapp
      - vol_web_bundle:/usr/local/bundle
      - vol_web_node_modules:/myapp/node_modules
volumes:
  vol_db:
  vol_web_bundle:
  vol_web_node_modules:
